version: "3"

services:
  web_service:
    container_name: socialnetwork-backend-demo
    image: socialnetwork-backend-demo:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/code:cached
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - ../.env
